# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  TF_VERSION: 'latest'

stages:
  - stage: setup
    jobs:
      - job: 
        continueOnError: false
        steps:
          - task: UsePythonVersion@0
            inputs:
              versionSpec: '3.x'
              addToPath: true
          - script: |
              python -m pip install --upgrade pip
              pip install awscli
          - task: DownloadSecureFile@1
            name: azServicePrincipal
            inputs:
              secureFile: 'azure-sp.json'  # Replace with the name of your service principal file
          - script: |
              # Fetch secrets from Azure Key Vault
              client_id=$(az keyvault secret show --vault-name <your-keyvault-name> --name "ServicePrincipalClientId" --query "value" -o tsv)
              client_secret=$(az keyvault secret show --vault-name <your-keyvault-name> --name "ServicePrincipalClientSecret" --query "value" -o tsv)
              tenant_id=$(az keyvault secret show --vault-name <your-keyvault-name> --name "ServicePrincipalTenantId" --query "value" -o tsv)

              # Use secrets in your commands (e.g., login to Azure)
              az login --service-principal -u $client_id -p $client_secret --tenant $tenant_id
            displayName: 'Login to Azure with Service Principal'
          
          - script: |
              aws_access_key_id=$(az keyvault secret show --vault-name azpipelinevault --name "AWSAccessKeyId" --query "value" -o tsv)
              aws_secret_access_key=$(az keyvault secret show --vault-name azpipelinevault --name "AWSSecretAccessKey" --query "value" -o tsv)
              aws configure set aws_access_key_id $aws_access_key_id
              aws configure set aws_secret_access_key $aws_secret_access_key
          - task: TerraformInstaller@1
            displayName: Install Terraform
            inputs:
              terraformVersion: 'latest'

          - script: |
              terraform init
            displayName: 'Terraform init'

          - script: |
              terraform validate
            displayName: 'Terraform validate'

          - script: |
              terraform plan -out=tfplan
            displayName: 'Terraform plan'

          - script: |
              terraform apply -auto-approve tfplan
            displayName: 'Terraform apply'

          - task: AzureKeyVault@2
            inputs:
              azureSubscription: AzurePipelineServiceConnection # Replace with your Azure subscription
              KeyVaultName: 'azpipelinevault'  # Replace with your Key Vault name
              SecretsFilter: '*'
              RunAsPreJob: true

          - script: |
              # Verify resources creation
              terraform output
            displayName: 'Verify Terraform outputs'
